### ISSUE TITLE
Pick a lang

### ISSUE THREAD

**Issue by nickolasacosta** [revuniversal/stig-service#6]
Pick a lang Mr Stigs.

**Comment by jpdillingham** [comment]
My vote would be .NET Core or node.  Have we decided how this will be hosted?

**Comment by nickolasacosta** [comment]
I'm down for either but If node is chosen I would prefer Typescript.  

I have no preference on hosting.

**Comment by revuniversal** [comment]
Typescript sounds good to me.  Hadn't really considered hosting yet.
